#!/usr/bin/ruby
if File.exist?(File.join(__dir__,'..','lib','cpee','implementation.rb'))
  require_relative File.join(__dir__,'..','lib','cpee','implementation')
elsif File.exist?(File.join(Dir.home,'Projects','cpee','lib','cpee','implementation.rb'))
  require_relative File.join(Dir.home, 'Projects','cpee','lib','cpee','implementation')
else
  require 'cpee/implementation'
end

Riddl::Server.new(CPEE::SERVER, :host => 'localhost', :port => 8298) do |opts|
  opts[:instances]          = File.join(__dir__,'instances')
  opts[:executionhandlers]  = File.join(__dir__,'executionhandlers')
  opts[:notifications_init] = File.join(__dir__,'resources','notifications')
  opts[:properties_init]    = File.join(__dir__,'resources','properties.init')

  accessible_description true
  cross_site_xhr true
  process_out false

  use CPEE::implementation(opts)
end.loop!
