#!/usr/bin/ruby
require 'rubygems'
require 'riddl/server'
require 'xml/smart'
require 'base64'
require 'pp'
require 'uri'

require_relative '../testset'

class Instantiate < Riddl::Implementation
  def response
    cpee = @a[0]
    tdoc = @p[@p.length - 1].value.read
    if @p[0].additional =~ /base64/
      tdoc = Base64.decode64(tdoc)
    end

    ins = Testset::load(tdoc,cpee)

    # params << Riddl::Parameter::Simple.new("name",'state')
    # params << Riddl::Parameter::Simple.new("value","running")
        status, response = res.put params
        return Riddl::Parameter::Simple.new("url",$cpee + ins)
      end
    end

    @status = 500
  end
end

Riddl::Server.new(File.dirname(__FILE__) + '/instantiation.xml', :port => 9296, :debug => STDOUT) do
  accessible_description true
  cross_site_xhr true

  @riddl_opts[:cpee] ||= 'http://localhost:9298/'

  on resource do
    run Instantiate, @riddl_opts[:cpee] if post 'instantiate'
  end
end.loop!
