#!/usr/bin/ruby
require 'weel'
require 'yaml'
if File.exists? '../lib/cpee/controller.rb'
  require '../lib/cpee/controller'
else
  require 'cpee/controller'
end
require_relative 'handlerwrappers/default'
require_relative 'instance'

opts = YAML::load_file(File.join(__dir__,'opts.yaml'))
controller = CPEE::Controller.new(File.basename(__dir__).to_i, __dir__, opts)
controller.instance = Instance.new controller
controller.start
