#!/usr/bin/ruby
require '../../../../riddl/lib/ruby/client'

srv = Riddl::Client.new("http://localhost:9298/")

# === Generate Wee-Instances
main = srv.resource("/")

status, res = main.post [
  Riddl::Parameter::Simple.new("name","demo")
]
