#!/usr/bin/ruby
require '../../../../riddl/lib/ruby/client'

srv = Riddl::Client.new("http://localhost:9298/")

# === Generate Wee-Instances
main = srv.resource("/1/notifications/subscriptions")

status, res = main.post [
  Riddl::Parameter::Simple.new("url","http://www.pri.univie.ac.at/~mangler/monitor.php"),
  Riddl::Parameter::Simple.new("topic",'monitoring'),
  Riddl::Parameter::Simple.new("events","activity_call,activity_manipulate,activity_done,activity_failed"),
  Riddl::Parameter::Simple.new("topic",'properties/description'),
  Riddl::Parameter::Simple.new("events","change,error"),
  Riddl::Parameter::Simple.new("topic",'properties/state'),
  Riddl::Parameter::Simple.new("events","change"),
  Riddl::Parameter::Simple.new("topic",'properties/state'),
  Riddl::Parameter::Simple.new("votes","start"),
  Riddl::Parameter::Simple.new("topic",'properties/context-variables'),
  Riddl::Parameter::Simple.new("events","change"),
  Riddl::Parameter::Simple.new("topic",'properties/endpoints'),
  Riddl::Parameter::Simple.new("events","change"),
  Riddl::Parameter::Simple.new("topic",'properties/handlers'),
  Riddl::Parameter::Simple.new("events","change")
]
