#!/usr/bin/ruby
require '../../../../riddl/lib/ruby/client'

srv = Riddl::Client.new("http://localhost:9298/")

# === Generate Wee-Instances
main = srv.resource("/1/properties/values/context-variables")

status, res = main.post [ 
  Riddl::Parameter::Simple.new("key","x"),
  Riddl::Parameter::Simple.new("value","_begin") 
]
