#!/usr/bin/ruby
require '../../../../riddl/lib/ruby/client'

srv = Riddl::Client.new("http://localhost:9292/")

# === Generate Wee-Instances
main = srv.resource("/1/properties/values/description")

status, res = main.put [ 
  Riddl::Parameter::Simple.new("value","activity :a1, :call, :timeout, :resource => '/', :method => 'get', :parameters => [ { :timeout => 6 } ]")
]
