#!/usr/bin/ruby
require '../../../../riddl/lib/ruby/client'

srv = Riddl::Client.new("http://localhost:9292/")

# === Generate Wee-Instances
main = srv.resource("/1/properties/values/endpoints")

status, res = main.post [ 
  Riddl::Parameter::Simple.new("key","timeout"),
  Riddl::Parameter::Simple.new("value","http://www.pri.univie.ac.at/~mangler/timeout.php") 
]
