#!/usr/bin/ruby
require '../../../../riddl/lib/ruby/client'

srv = Riddl::Client.new("http://localhost:9292/")

main = srv.resource("/1/properties/values/endpoints/timeout")

status, res = main.delete
