#!/usr/bin/ruby
require '../../../../riddl/lib/ruby/client'

srv = Riddl::Client.new("http://localhost:9292/")

# === Generate Wee-Instances
main = srv.resource("/1/properties/values/state")

status, res = main.put [ 
  Riddl::Parameter::Simple.new("value","running")
]
