#!/usr/bin/ruby
require 'rubygems'
require 'riddl/server'

class DoIt < Riddl::Implementation
  def response
    p @p
    nil
  end
end

Riddl::Server.new(File.dirname(__FILE__) + '/replay.xml', :port => 9315) do
  accessible_description false

  on resource do
    run DoIt if post
  end

end.loop!
