#! /bin/bash
CDIR=$(dirname $0)
BIN_DIR="$CDIR/target/release"
# Go into instance dir
cd $CDIR
INSTANCE_ID=$(grep -Po '(?<=\"instance_id\": )(\d+)' opts.json)
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$BIN_DIR:$(rustc --print=sysroot)/lib:$(rustc --print=sysroot)/lib/rustlib/x86_64-unknown-linux-gnu/lib
exec "$BIN_DIR/weel_bin_$INSTANCE_ID"
