<element xmlns="http://relaxng.org/ns/structure/1.0" xmlns:rngui="http://rngui.org" rngui:version="1.2" name="manipulate" rngui:label="Script" datatypeLibrary="http://www.w3.org/2001/XMLSchema-datatypes" ns="http://cpee.org/ns/description/1.0">
  <attribute name="id" rngui:label="ID" rngui:default="javascript:get_free_id()">
    <data type="string" rngui:readonly="true"/>
  </attribute>
  <attribute name="label" rngui:label="Label">
    <data type="string" rngui:label="Short description of the task"/>
  </attribute>
  <attribute name="color" rngui:label="Task Color">
    <choice rngui:type='color'>
      <value>#ffffff</value>
      <value>#99c1f1</value>
      <value>#8ff0a4</value>
      <value>#f9f06b</value>
      <value>#ffbe6f</value>
      <value>#f66151</value>
      <value>#dc8add</value>
      <value>#cdab8f</value>
      <value>#77767b</value>
    </choice>
  </attribute>
  <text rngui:label="Script that is executed"/>
</element>
