
require 'test/unit'
require ::File.dirname(__FILE__) + '/tc_handler'
require ::File.dirname(__FILE__) + '/tc_wf_control'
require ::File.dirname(__FILE__) + '/tc_codereplace'
require ::File.dirname(__FILE__) + '/tc_search'
require ::File.dirname(__FILE__) + '/tc_context'
require ::File.dirname(__FILE__) + '/tc_endpoint'
require ::File.dirname(__FILE__) + '/tc_state'
require ::File.dirname(__FILE__) + '/tc_parallel'
require ::File.dirname(__FILE__) + '/tc_choose'
